$env:DOTNET_ROOT = Join-Path $PSScriptRoot '../.tools/dotnet'
$env:DOTNET_CLI_HOME = Join-Path $PSScriptRoot '../.tools/cli'
$env:NUGET_PACKAGES = Join-Path $PSScriptRoot '../.tools/packages'
$env:DOTNET_CLI_TELEMETRY_OPTOUT = '1'
$env:DOTNET_SKIP_FIRST_TIME_EXPERIENCE = '1'
$env:DOTNET_NOLOGO = '1'
