namespace Alchemist.Core;

public enum ForgeKind { Attack, Skill, Power }
public enum ForgeTarget { Self, Enemy, AllEnemies }

// Stable formula IDs are saved on one card model; names and display text never act as keys.
// Materials is unordered and allows repeats; commons use 2, uncommons 3, rares 4 (AlchemyState.Recipes).
public sealed record ForgeFormula(string Id, string Name, IReadOnlyList<Material> Materials,
    string Role, string Plan, int Cost, ForgeKind Kind, ForgeTarget Target,
    string Text, IReadOnlyDictionary<string,int> Values, IReadOnlyDictionary<string,int> Upgrade,
    bool Exhaust = false, bool Retain = false, AlchemyPhase? ElementOverride = null)
{
    /// The phase this card enters when played. Derived from the materials unless the formula names one.
    public AlchemyPhase Element => ElementOverride ?? PhaseRules.FromMaterials(Materials);
    public string Describe(bool upgraded = false)
    {
        string result = Text;
        foreach (var (key,value) in Values)
            result = result.Replace("{"+key+":diff()}", (value + (upgraded ? Upgrade.GetValueOrDefault(key) : 0)).ToString());
        return result;
    }
    public string Preview => $"{Cost}コスト / {Kind switch { ForgeKind.Attack => "アタック", ForgeKind.Skill => "スキル", _ => "パワー" }} / {Target switch { ForgeTarget.Enemy => "敵1体", ForgeTarget.AllEnemies => "敵全体", _ => "自身" }} / {PhaseRules.Name(Element)}相\n"
        + Describe() + (Retain ? "\n保留。" : "") + (Exhaust ? "\n廃棄。" : "") + "\n強化後：" + Describe(true);
}

public static class ForgeCatalog
{
    public static readonly IReadOnlyList<ForgeFormula> All = Array.AsReadOnly(new ForgeFormula[] {
        new("greatblade.v1","錬鉄の大剣",[Material.Iron,Material.Iron],"切り札","保留して弱体を待ち、大きな一撃と防御を両立。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "{Damage:diff()}ダメージ。{Block:diff()}ブロックを得る。",
            new Dictionary<string,int>{{"Damage",28},{"Block",8}}, new Dictionary<string,int>{{"Damage",8},{"Block",4}},Retain:true),
        new("siege_shell.v1","徹甲榴弾",[Material.Iron,Material.Powder],"切り札","先に弱体を入れてから命中。次の攻撃も通しやすくする。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "弱体{VulnerablePower:diff()}を与え、その後{Damage:diff()}ダメージ。",
            new Dictionary<string,int>{{"Damage",14},{"VulnerablePower",1}}, new Dictionary<string,int>{{"Damage",4},{"VulnerablePower",1}}),
        new("recycling_reactor.v1","循環錬成炉",[Material.Iron,Material.Ether],"デッキの軸","炉の起動や廃棄カードを、ドローと防御に変える。",2,ForgeKind.Power,ForgeTarget.Self,
            "カードを廃棄するたび、{ExhaustBlock:diff()}ブロックを得る。",
            new Dictionary<string,int>{{"ExhaustBlock",3}}, new Dictionary<string,int>{{"ExhaustBlock",2}}),
        new("virulent_culture.v1","猛毒培養槽",[Material.Herb,Material.Herb],"デッキの軸","守っている間も毒を重ねる、長期戦の勝ち筋。",1,ForgeKind.Power,ForgeTarget.Self,
            "自分のターン開始時、敵全体に毒{Fumes:diff()}を与える。",
            new Dictionary<string,int>{{"Fumes",4}}, new Dictionary<string,int>{{"Fumes",2}}),
        new("toxic_blast.v1","毒霧爆弾",[Material.Herb,Material.Powder],"集団戦","全体攻撃と毒を一枚で。培養槽と合わせて継続ダメージ。",1,ForgeKind.Attack,ForgeTarget.AllEnemies,
            "敵全体に{Damage:diff()}ダメージと毒{PoisonPower:diff()}を与える。",
            new Dictionary<string,int>{{"Damage",6},{"PoisonPower",3}}, new Dictionary<string,int>{{"Damage",2},{"PoisonPower",1}}),
        new("distilled_venom.v1","濃縮毒液",[Material.Herb,Material.Ether],"切り札","保留できる大きな毒。ボスへ投入し、防御に専念する。",1,ForgeKind.Skill,ForgeTarget.Enemy,
            "毒{PoisonPower:diff()}を与える。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"PoisonPower",8},{"Cards",1}}, new Dictionary<string,int>{{"PoisonPower",3}},Exhaust:true,Retain:true),
        new("aether_nova.v1","エーテル爆縮",[Material.Powder,Material.Ether],"切り札","危険な集団戦で大きく削り、引いたカードで攻勢を続ける。",1,ForgeKind.Attack,ForgeTarget.AllEnemies,
            "敵全体に{Damage:diff()}ダメージ。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Damage",8},{"Cards",1}}, new Dictionary<string,int>{{"Damage",3}},Exhaust:true),

        new("alloy_flurry.v1","合金乱舞",[Material.Iron,Material.Iron],"多段攻撃","筋力を得てから使う主役。低い打点を何度も叩き込む。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "{Damage:diff()}ダメージを{Hits:diff()}回与える。",
            new Dictionary<string,int>{{"Damage",6},{"Hits",4}}, new Dictionary<string,int>{{"Damage",2}}),
        new("adamant_tonic.v1","金剛の霊薬",[Material.Iron,Material.Iron],"自己強化","筋力を恒久的に高め、多段攻撃を育てる。",1,ForgeKind.Power,ForgeTarget.Self,
            "筋力{StrengthPower:diff()}を得る。",
            new Dictionary<string,int>{{"StrengthPower",3}}, new Dictionary<string,int>{{"StrengthPower",1}}),
        new("war_elixir.v1","戦支度の霊薬",[Material.Iron,Material.Herb],"自己強化","攻撃と防御を同時に底上げし、デッキ全体を主役にする。",2,ForgeKind.Power,ForgeTarget.Self,
            "筋力{StrengthPower:diff()}と敏捷{DexterityPower:diff()}を得る。",
            new Dictionary<string,int>{{"StrengthPower",2},{"DexterityPower",2}}, new Dictionary<string,int>{{"StrengthPower",1},{"DexterityPower",1}}),
        new("serrated_barrage.v1","鋸刃連射",[Material.Iron,Material.Herb],"多段攻撃","先に弱体を付け、続く連撃と後続の攻撃を通す。",1,ForgeKind.Attack,ForgeTarget.Enemy,
            "弱体{VulnerablePower:diff()}を与え、{Damage:diff()}ダメージを{Hits:diff()}回与える。",
            new Dictionary<string,int>{{"VulnerablePower",1},{"Damage",4},{"Hits",4}}, new Dictionary<string,int>{{"Damage",1},{"Hits",1}}),
        new("rotary_cannon.v1","回転式錬金砲",[Material.Iron,Material.Powder],"多段攻撃","筋力を一発ごとに乗せる六連射。単体の敵を削り切る。",1,ForgeKind.Attack,ForgeTarget.Enemy,
            "{Damage:diff()}ダメージを{Hits:diff()}回与える。",
            new Dictionary<string,int>{{"Damage",3},{"Hits",6}}, new Dictionary<string,int>{{"Damage",1}}),
        new("blast_plating.v1","爆圧装甲",[Material.Iron,Material.Powder],"攻防一体","その場を守りながら、以降の攻撃を強化する。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。筋力{StrengthPower:diff()}を得る。",
            new Dictionary<string,int>{{"Block",14},{"StrengthPower",2}}, new Dictionary<string,int>{{"Block",5},{"StrengthPower",1}},Exhaust:true),
        new("reinforcement_matrix.v1","補強行列",[Material.Iron,Material.Ether],"自己強化","敏捷を高め、軽い防御カードにも終盤の役割を持たせる。",1,ForgeKind.Power,ForgeTarget.Self,
            "敏捷{DexterityPower:diff()}を得る。",
            new Dictionary<string,int>{{"DexterityPower",3}}, new Dictionary<string,int>{{"DexterityPower",1}}),
        new("kinetic_loop.v1","運動連鎖",[Material.Iron,Material.Ether],"多段攻撃","三連撃から次のカードへ繋ぎ、強化した筋力を回転させる。",1,ForgeKind.Attack,ForgeTarget.Enemy,
            "{Damage:diff()}ダメージを{Hits:diff()}回与える。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Damage",6},{"Hits",3},{"Cards",1}}, new Dictionary<string,int>{{"Damage",2}}),
        new("footwork_distillate.v1","軽業の蒸留液",[Material.Herb,Material.Herb],"自己強化","敏捷に特化し、毒が敵を倒すまでの守りを固める。",1,ForgeKind.Power,ForgeTarget.Self,
            "敏捷{DexterityPower:diff()}を得る。",
            new Dictionary<string,int>{{"DexterityPower",3}}, new Dictionary<string,int>{{"DexterityPower",2}}),
        new("venom_needles.v1","毒針斉射",[Material.Herb,Material.Powder],"多段攻撃","連撃で筋力を活かしながら、毒の勝ち筋も進める。",1,ForgeKind.Attack,ForgeTarget.Enemy,
            "{Damage:diff()}ダメージを{Hits:diff()}回与える。毒{PoisonPower:diff()}を与える。",
            new Dictionary<string,int>{{"Damage",2},{"Hits",5},{"PoisonPower",6}}, new Dictionary<string,int>{{"Damage",1},{"PoisonPower",3}}),
        new("berserker_catalyst.v1","闘争触媒",[Material.Herb,Material.Powder],"自己強化","筋力を得て手札を繋ぐ、攻撃型デッキの始動薬。",1,ForgeKind.Power,ForgeTarget.Self,
            "筋力{StrengthPower:diff()}を得る。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"StrengthPower",2},{"Cards",1}}, new Dictionary<string,int>{{"StrengthPower",1},{"Cards",1}}),
        new("quicksilver_draft.v1","水銀の早飲み",[Material.Herb,Material.Ether],"即応強化","敏捷と手札を一度に整え、守りへ素早く移る。",1,ForgeKind.Skill,ForgeTarget.Self,
            "敏捷{DexterityPower:diff()}を得る。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"DexterityPower",2},{"Cards",2}}, new Dictionary<string,int>{{"DexterityPower",1},{"Cards",1}},Exhaust:true),
        new("chain_detonation.v1","連鎖爆轟",[Material.Powder,Material.Powder],"多段全体攻撃","敵全体へ三度爆発を浴びせ、筋力を全体火力に変える。",2,ForgeKind.Attack,ForgeTarget.AllEnemies,
            "敵全体に{Damage:diff()}ダメージを{Hits:diff()}回与える。",
            new Dictionary<string,int>{{"Damage",7},{"Hits",3}}, new Dictionary<string,int>{{"Damage",2}},Exhaust:true),
        new("gunpowder_rhythm.v1","火薬律動",[Material.Powder,Material.Powder],"自己強化","攻撃を重くし、連射・爆轟の全段を強化する。",1,ForgeKind.Power,ForgeTarget.Self,
            "筋力{StrengthPower:diff()}を得る。",
            new Dictionary<string,int>{{"StrengthPower",2}}, new Dictionary<string,int>{{"StrengthPower",2}}),
        new("star_barrage.v1","星屑弾幕",[Material.Powder,Material.Ether],"多段攻撃","五連撃の後も手札を補充し、攻勢を止めない。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "{Damage:diff()}ダメージを{Hits:diff()}回与える。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Damage",5},{"Hits",5},{"Cards",1}}, new Dictionary<string,int>{{"Damage",1},{"Cards",1}}),
        new("aetheric_form.v1","霊質変成",[Material.Ether,Material.Ether],"自己強化","筋力と敏捷を同時に得る、攻守両用の変成。",2,ForgeKind.Power,ForgeTarget.Self,
            "筋力{StrengthPower:diff()}と敏捷{DexterityPower:diff()}を得る。",
            new Dictionary<string,int>{{"StrengthPower",2},{"DexterityPower",2}}, new Dictionary<string,int>{{"StrengthPower",1},{"DexterityPower",1}}),

        // Uncommon tier: 3 materials, unordered, repeats allowed (20 = 4 mono + 4 all-distinct + 12 two-plus-one).
        new("u_iii.v1","鋼纏の重甲",[Material.Iron,Material.Iron,Material.Iron],"自己強化","鉄を惜しみなく使い、防御と筋力を同時に積む重装の型。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。筋力{StrengthPower:diff()}を得る。",
            new Dictionary<string,int>{{"Block",24},{"StrengthPower",3}}, new Dictionary<string,int>{{"Block",6},{"StrengthPower",1}}),
        new("u_hhh.v1","猛毒の瘴気",[Material.Herb,Material.Herb,Material.Herb],"デッキの軸","培養槽をさらに濃縮し、毒だけで押し切る型。",2,ForgeKind.Power,ForgeTarget.Self,
            "自分のターン開始時、敵全体に毒{Fumes:diff()}を与える。",
            new Dictionary<string,int>{{"Fumes",7}}, new Dictionary<string,int>{{"Fumes",3}}),
        new("u_ppp.v1","業火の一斉射",[Material.Powder,Material.Powder,Material.Powder],"切り札","一度きりの大爆発で盤面を制圧する。",2,ForgeKind.Attack,ForgeTarget.AllEnemies,
            "敵全体に{Damage:diff()}ダメージ。",
            new Dictionary<string,int>{{"Damage",26}}, new Dictionary<string,int>{{"Damage",8}},Exhaust:true),
        new("u_eee.v1","深奥の霊光",[Material.Ether,Material.Ether,Material.Ether],"守りと循環","一気に手札を整えてから防御に専念する。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Block",10},{"Cards",4}}, new Dictionary<string,int>{{"Cards",1}},Exhaust:true),
        new("u_ihp.v1","鉄毒火の乱撃",[Material.Iron,Material.Herb,Material.Powder],"攻撃の準備","弱体・直接打撃・毒を一枚に凝縮する。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "弱体{VulnerablePower:diff()}を与え、{Damage:diff()}ダメージ。毒{PoisonPower:diff()}を与える。",
            new Dictionary<string,int>{{"VulnerablePower",2},{"Damage",18},{"PoisonPower",4}}, new Dictionary<string,int>{{"Damage",6}}),
        new("u_ihe.v1","鎮痛の秘薬",[Material.Iron,Material.Herb,Material.Ether],"守りと循環","守りを固めながら次の手番の手数を増やす。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。敏捷{DexterityPower:diff()}を得る。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Block",10},{"DexterityPower",2},{"Cards",1}}, new Dictionary<string,int>{{"Block",4}}),
        new("u_ipe.v1","回生の砲撃",[Material.Iron,Material.Powder,Material.Ether],"切り札","一撃を叩き込みつつ、廃棄して手札を整える。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "{Damage:diff()}ダメージ。カードを{Cards:diff()}枚引く。相を{AdvancePhase:diff()}つ進める（地→水→火→風）。",
            new Dictionary<string,int>{{"Damage",16},{"Cards",1},{"AdvancePhase",1}}, new Dictionary<string,int>{{"Damage",5}},Exhaust:true),
        new("u_hpe.v1","毒煙の残響",[Material.Herb,Material.Powder,Material.Ether],"集団戦","全体攻撃と毒に、引き込みまで添える。",2,ForgeKind.Attack,ForgeTarget.AllEnemies,
            "敵全体に{Damage:diff()}ダメージと毒{PoisonPower:diff()}を与える。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Damage",9},{"PoisonPower",4},{"Cards",1}}, new Dictionary<string,int>{{"Damage",3}}),
        new("u_iih.v1","鉄毒の武装帯",[Material.Iron,Material.Iron,Material.Herb],"自己強化","鉄の守りに毒草のしなやかさを添え、隙のない構えを作る。",1,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。筋力{StrengthPower:diff()}を得る。敏捷{DexterityPower:diff()}を得る。",
            new Dictionary<string,int>{{"Block",14},{"StrengthPower",2},{"DexterityPower",2}}, new Dictionary<string,int>{{"Block",4}}),
        new("u_iip.v1","熔鉄の胸甲",[Material.Iron,Material.Iron,Material.Powder],"自己強化","鉄に火薬の熱を通し、筋力を余分に鍛える。",1,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。筋力{StrengthPower:diff()}を得る。",
            new Dictionary<string,int>{{"Block",14},{"StrengthPower",3}}, new Dictionary<string,int>{{"Block",4}}),
        new("u_iie.v1","整流の鉄壁",[Material.Iron,Material.Iron,Material.Ether],"守りと循環","守りを固めた勢いで一枚引き、手を途切れさせない。",1,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。筋力{StrengthPower:diff()}を得る。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Block",14},{"StrengthPower",2},{"Cards",1}}, new Dictionary<string,int>{{"Block",4}}),
        new("u_ihh.v1","毒衣の鉄棘",[Material.Iron,Material.Herb,Material.Herb],"攻撃の準備","毒を仕込みながら、その場をしっかり守る。",1,ForgeKind.Skill,ForgeTarget.Enemy,
            "毒{PoisonPower:diff()}を与える。{Block:diff()}ブロックを得る。",
            new Dictionary<string,int>{{"PoisonPower",10},{"Block",4}}, new Dictionary<string,int>{{"PoisonPower",4}}),
        new("u_hhp.v1","瘴煙の一突き",[Material.Herb,Material.Herb,Material.Powder],"攻撃の準備","毒を刻んでから、火薬の追撃で仕上げる。",1,ForgeKind.Attack,ForgeTarget.Enemy,
            "毒{PoisonPower:diff()}を与える。{Damage:diff()}ダメージ。",
            new Dictionary<string,int>{{"PoisonPower",10},{"Damage",6}}, new Dictionary<string,int>{{"PoisonPower",4}}),
        new("u_hhe.v1","霧毒の看破",[Material.Herb,Material.Herb,Material.Ether],"切り札","毒を撒きながら、次の一手を引き込む。",1,ForgeKind.Skill,ForgeTarget.Enemy,
            "毒{PoisonPower:diff()}を与える。カードを{Cards:diff()}枚引く。相を{AdvancePhase:diff()}つ進める（地→水→火→風）。",
            new Dictionary<string,int>{{"PoisonPower",8},{"Cards",1},{"AdvancePhase",1}}, new Dictionary<string,int>{{"PoisonPower",3}}),
        new("u_ipp.v1","砲身の鉄楯",[Material.Iron,Material.Powder,Material.Powder],"攻防一体","大きく撃ち抜きつつ、その場も固める。",1,ForgeKind.Attack,ForgeTarget.Enemy,
            "{Damage:diff()}ダメージを{Hits:diff()}回与える。{Block:diff()}ブロックを得る。",
            new Dictionary<string,int>{{"Damage",4},{"Hits",3},{"Block",4}}, new Dictionary<string,int>{{"Damage",1}}),
        new("u_hpp.v1","崩爆の連弾",[Material.Herb,Material.Powder,Material.Powder],"攻撃の準備","弱体を刻んでから、大きく撃ち抜く。",1,ForgeKind.Attack,ForgeTarget.Enemy,
            "弱体{VulnerablePower:diff()}を与え、{Damage:diff()}ダメージ。",
            new Dictionary<string,int>{{"VulnerablePower",2},{"Damage",17}}, new Dictionary<string,int>{{"Damage",6}}),
        new("u_ppe.v1","疾爆の一撃",[Material.Powder,Material.Powder,Material.Ether],"切り札","大きな一撃の後、勢いのまま引き込む。",1,ForgeKind.Attack,ForgeTarget.Enemy,
            "{Damage:diff()}ダメージ。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Damage",17},{"Cards",1}}, new Dictionary<string,int>{{"Damage",6}}),
        new("u_iee.v1","静謐の鉄扉",[Material.Iron,Material.Ether,Material.Ether],"守りと循環","鉄の重みでさらに守りを固めた瞑想。",1,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Block",10},{"Cards",2}}, new Dictionary<string,int>{{"Block",4}}),
        new("u_hee.v1","風毒の静息",[Material.Herb,Material.Ether,Material.Ether],"守りと循環","身を守りながら軽やかさを養う瞑想。",1,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。カードを{Cards:diff()}枚引く。敏捷{DexterityPower:diff()}を得る。",
            new Dictionary<string,int>{{"Block",6},{"Cards",2},{"DexterityPower",2}}, new Dictionary<string,int>{{"Block",3}}),
        new("u_pee.v1","火霊の残響",[Material.Powder,Material.Ether,Material.Ether],"守りと循環","静けさの中に、次の一撃への活力を残す。",1,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。カードを{Cards:diff()}枚引く。筋力{StrengthPower:diff()}を得る。",
            new Dictionary<string,int>{{"Block",6},{"Cards",2},{"StrengthPower",1}}, new Dictionary<string,int>{{"Block",3}}),

        // Rare tier: 4 materials, unordered, repeats allowed (35 = 4 mono + 12 three-plus-one + 6 two-plus-two
        // + 12 two-plus-one-plus-one + 1 all-four).
        new("r_iiii.v1","皆伝・鋼の城壁",[Material.Iron,Material.Iron,Material.Iron,Material.Iron],"自己強化","鉄の全てを注ぎ込む、一度きりの絶対防御。",3,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。筋力{StrengthPower:diff()}を得る。",
            new Dictionary<string,int>{{"Block",34},{"StrengthPower",5}}, new Dictionary<string,int>{{"Block",8}},Exhaust:true),
        new("r_hhhh.v1","皆伝・疫毒の坩堝",[Material.Herb,Material.Herb,Material.Herb,Material.Herb],"デッキの軸","培養槽の完成形。触れるもの全てを腐らせる猛毒炉。",2,ForgeKind.Power,ForgeTarget.Self,
            "自分のターン開始時、敵全体に毒{Fumes:diff()}を与える。",
            new Dictionary<string,int>{{"Fumes",10}}, new Dictionary<string,int>{{"Fumes",4}}),
        new("r_pppp.v1","皆伝・大業火",[Material.Powder,Material.Powder,Material.Powder,Material.Powder],"切り札","全火薬を注ぎ込む、盤面を焼き尽くす最終爆発。",3,ForgeKind.Attack,ForgeTarget.AllEnemies,
            "敵全体に{Damage:diff()}ダメージ。",
            new Dictionary<string,int>{{"Damage",40}}, new Dictionary<string,int>{{"Damage",10}},Exhaust:true),
        new("r_eeee.v1","皆伝・虚空の書",[Material.Ether,Material.Ether,Material.Ether,Material.Ether],"守りと循環","手札を根こそぎ引き直す、一度きりの大瞑想。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Block",14},{"Cards",6}}, new Dictionary<string,int>{{"Cards",2}},Exhaust:true),
        new("r_iiih.v1","鋼身秘薬の型",[Material.Iron,Material.Iron,Material.Iron,Material.Herb],"自己強化","鉄の鎧に薬草のしなやかさを一滴。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。筋力{StrengthPower:diff()}を得る。敏捷{DexterityPower:diff()}を得る。",
            new Dictionary<string,int>{{"Block",20},{"StrengthPower",3},{"DexterityPower",2}}, new Dictionary<string,int>{{"Block",5}}),
        new("r_iiip.v1","熔鋼の重殻",[Material.Iron,Material.Iron,Material.Iron,Material.Powder],"自己強化","鉄に火薬の熱を通し、筋力をさらに鍛え上げる。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。筋力{StrengthPower:diff()}を得る。",
            new Dictionary<string,int>{{"Block",20},{"StrengthPower",4}}, new Dictionary<string,int>{{"Block",5}}),
        new("r_iiie.v1","整流の重鎧",[Material.Iron,Material.Iron,Material.Iron,Material.Ether],"守りと循環","鉄壁の勢いのまま、一枚引き込む。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。筋力{StrengthPower:diff()}を得る。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Block",20},{"StrengthPower",3},{"Cards",1}}, new Dictionary<string,int>{{"Block",5}}),
        new("r_hhhi.v1","鉄衣の毒霧",[Material.Herb,Material.Herb,Material.Herb,Material.Iron],"攻撃の準備","毒を存分に撒きながら、身も固める。",2,ForgeKind.Skill,ForgeTarget.Enemy,
            "毒{PoisonPower:diff()}を与える。{Block:diff()}ブロックを得る。",
            new Dictionary<string,int>{{"PoisonPower",16},{"Block",5}}, new Dictionary<string,int>{{"PoisonPower",6}}),
        new("r_hhhp.v1","猛毒の炸裂弾",[Material.Herb,Material.Herb,Material.Herb,Material.Powder],"攻撃の準備","濃縮した毒に、火薬の追撃を添える。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "毒{PoisonPower:diff()}を与える。{Damage:diff()}ダメージ。",
            new Dictionary<string,int>{{"PoisonPower",16},{"Damage",7}}, new Dictionary<string,int>{{"PoisonPower",6}}),
        new("r_hhhe.v1","毒霞の看破",[Material.Herb,Material.Herb,Material.Herb,Material.Ether],"切り札","毒を撒き切り、次の一手を引き込む。",2,ForgeKind.Skill,ForgeTarget.Enemy,
            "毒{PoisonPower:diff()}を与える。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"PoisonPower",16},{"Cards",1}}, new Dictionary<string,int>{{"PoisonPower",6}}),
        new("r_pppi.v1","重砲の鉄盾",[Material.Powder,Material.Powder,Material.Powder,Material.Iron],"攻防一体","大爆発の反動を、鉄の構えで受け止める。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "{Damage:diff()}ダメージを{Hits:diff()}回与える。{Block:diff()}ブロックを得る。",
            new Dictionary<string,int>{{"Damage",5},{"Hits",5},{"Block",5}}, new Dictionary<string,int>{{"Damage",1}}),
        new("r_ppph.v1","崩爆の断罪弾",[Material.Powder,Material.Powder,Material.Powder,Material.Herb],"攻撃の準備","弱体を刻み込む、大火力の一撃。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "弱体{VulnerablePower:diff()}を与え、{Damage:diff()}ダメージ。",
            new Dictionary<string,int>{{"VulnerablePower",3},{"Damage",26}}, new Dictionary<string,int>{{"Damage",8}}),
        new("r_pppe.v1","疾爆の会心弾",[Material.Powder,Material.Powder,Material.Powder,Material.Ether],"切り札","大爆発の勢いで、次の手を引き込む。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "{Damage:diff()}ダメージ。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Damage",26},{"Cards",1}}, new Dictionary<string,int>{{"Damage",8}}),
        new("r_eeei.v1","静謐の鉄庫",[Material.Ether,Material.Ether,Material.Ether,Material.Iron],"守りと循環","鉄の重みを添えた、深い瞑想。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Block",13},{"Cards",3}}, new Dictionary<string,int>{{"Cards",1}}),
        new("r_eeeh.v1","風毒の深息",[Material.Ether,Material.Ether,Material.Ether,Material.Herb],"守りと循環","軽やかさを纏った、深い瞑想。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。カードを{Cards:diff()}枚引く。敏捷{DexterityPower:diff()}を得る。",
            new Dictionary<string,int>{{"Block",8},{"Cards",3},{"DexterityPower",2}}, new Dictionary<string,int>{{"Cards",1}}),
        new("r_eeep.v1","火霊の深息",[Material.Ether,Material.Ether,Material.Ether,Material.Powder],"守りと循環","静寂の中にも、活力の火種を残す。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。カードを{Cards:diff()}枚引く。筋力{StrengthPower:diff()}を得る。",
            new Dictionary<string,int>{{"Block",8},{"Cards",3},{"StrengthPower",1}}, new Dictionary<string,int>{{"Cards",1}}),
        new("r_iihh.v1","鉄毒の腐食輪",[Material.Iron,Material.Iron,Material.Herb,Material.Herb],"デッキの軸","筋力を蓄えながら、居座るだけで敵を腐らせる。",2,ForgeKind.Power,ForgeTarget.Self,
            "筋力{StrengthPower:diff()}を得る。自分のターン開始時、敵全体に毒{Fumes:diff()}を与える。",
            new Dictionary<string,int>{{"StrengthPower",3},{"Fumes",5}}, new Dictionary<string,int>{{"StrengthPower",1},{"Fumes",2}}),
        new("r_iipp.v1","鋼装砲撃",[Material.Iron,Material.Iron,Material.Powder,Material.Powder],"攻防一体","大きく撃ち抜きながら、なお守りを崩さない。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "{Damage:diff()}ダメージ。{Block:diff()}ブロックを得る。筋力{StrengthPower:diff()}を得る。",
            new Dictionary<string,int>{{"Damage",20},{"Block",8},{"StrengthPower",1}}, new Dictionary<string,int>{{"Damage",6}}),
        new("r_iiee.v1","重鎧の透徹",[Material.Iron,Material.Iron,Material.Ether,Material.Ether],"守りと循環","鉄の重みとエーテルの澄んだ流れを併せ持つ。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。筋力{StrengthPower:diff()}を得る。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Block",18},{"StrengthPower",2},{"Cards",2}}, new Dictionary<string,int>{{"Block",5}}),
        new("r_hhpp.v1","猛毒爆煙",[Material.Herb,Material.Herb,Material.Powder,Material.Powder],"集団戦","全体攻撃に濃い毒を乗せ、長期戦を制する。",2,ForgeKind.Attack,ForgeTarget.AllEnemies,
            "敵全体に{Damage:diff()}ダメージと毒{PoisonPower:diff()}を与える。",
            new Dictionary<string,int>{{"Damage",11},{"PoisonPower",8}}, new Dictionary<string,int>{{"Damage",4},{"PoisonPower",3}}),
        new("r_hhee.v1","風草の軽身",[Material.Herb,Material.Herb,Material.Ether,Material.Ether],"自己強化","敏捷を大きく高め、守りと引き込みも添える。",2,ForgeKind.Skill,ForgeTarget.Self,
            "敏捷{DexterityPower:diff()}を得る。{Block:diff()}ブロックを得る。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"DexterityPower",3},{"Block",6},{"Cards",2}}, new Dictionary<string,int>{{"DexterityPower",2}}),
        new("r_ppee.v1","疾爆の連引",[Material.Powder,Material.Powder,Material.Ether,Material.Ether],"切り札","大きな一撃の後、流れるように次を引く。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "{Damage:diff()}ダメージ。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Damage",22},{"Cards",2}}, new Dictionary<string,int>{{"Damage",7}}),
        new("r_iihp.v1","鉄毒火の重構え",[Material.Iron,Material.Iron,Material.Herb,Material.Powder],"自己強化","鉄の守りに毒草の俊敏、火薬の気迫を足す。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。筋力{StrengthPower:diff()}を得る。敏捷{DexterityPower:diff()}を得る。",
            new Dictionary<string,int>{{"Block",16},{"StrengthPower",3},{"DexterityPower",2}}, new Dictionary<string,int>{{"Block",4}}),
        new("r_iihe.v1","鉄毒風の巡り",[Material.Iron,Material.Iron,Material.Herb,Material.Ether],"守りと循環","守りと敏捷を整え、流れで一枚引く。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。筋力{StrengthPower:diff()}を得る。敏捷{DexterityPower:diff()}を得る。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Block",16},{"StrengthPower",2},{"DexterityPower",2},{"Cards",1}}, new Dictionary<string,int>{{"Block",4}}),
        new("r_iipe.v1","熔鉄の整流",[Material.Iron,Material.Iron,Material.Powder,Material.Ether],"守りと循環","熱した鉄の勢いで、なお一枚引き込む。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。筋力{StrengthPower:diff()}を得る。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Block",16},{"StrengthPower",3},{"Cards",1}}, new Dictionary<string,int>{{"Block",4}}),
        new("r_hhip.v1","鉄煙の毒撃",[Material.Herb,Material.Herb,Material.Iron,Material.Powder],"攻撃の準備","毒を仕込み、鉄と火薬で畳みかける。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "毒{PoisonPower:diff()}を与える。{Damage:diff()}ダメージ。{Block:diff()}ブロックを得る。",
            new Dictionary<string,int>{{"PoisonPower",12},{"Damage",6},{"Block",4}}, new Dictionary<string,int>{{"PoisonPower",4},{"Damage",3}}),
        new("r_hhie.v1","鉄風の毒霧",[Material.Herb,Material.Herb,Material.Iron,Material.Ether],"切り札","毒を広げながら、守りと手札も整える。",2,ForgeKind.Skill,ForgeTarget.Enemy,
            "毒{PoisonPower:diff()}を与える。{Block:diff()}ブロックを得る。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"PoisonPower",12},{"Block",4},{"Cards",1}}, new Dictionary<string,int>{{"PoisonPower",4}}),
        new("r_hhpe.v1","爆毒風の一投",[Material.Herb,Material.Herb,Material.Powder,Material.Ether],"攻撃の準備","毒と爆炎を撃ち込み、勢いで引き込む。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "毒{PoisonPower:diff()}を与える。{Damage:diff()}ダメージ。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"PoisonPower",12},{"Damage",6},{"Cards",1}}, new Dictionary<string,int>{{"PoisonPower",4},{"Damage",3}}),
        new("r_ppih.v1","鉄毒砲の一撃",[Material.Powder,Material.Powder,Material.Iron,Material.Herb],"攻撃の準備","弱体を刻みつつ、身を固めて撃ち抜く。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "弱体{VulnerablePower:diff()}を与え、{Damage:diff()}ダメージ。{Block:diff()}ブロックを得る。",
            new Dictionary<string,int>{{"VulnerablePower",2},{"Damage",20},{"Block",4}}, new Dictionary<string,int>{{"Damage",7}}),
        new("r_ppie.v1","鉄風の砲撃",[Material.Powder,Material.Powder,Material.Iron,Material.Ether],"攻防一体","大きく撃ち抜き、守りと手札も崩さない。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "{Damage:diff()}ダメージ。{Block:diff()}ブロックを得る。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"Damage",20},{"Block",4},{"Cards",1}}, new Dictionary<string,int>{{"Damage",7}}),
        new("r_pphe.v1","毒風の一斉射",[Material.Powder,Material.Powder,Material.Herb,Material.Ether],"切り札","弱体を刻んだ一撃の後、手を引き込む。",2,ForgeKind.Attack,ForgeTarget.Enemy,
            "弱体{VulnerablePower:diff()}を与え、{Damage:diff()}ダメージ。カードを{Cards:diff()}枚引く。",
            new Dictionary<string,int>{{"VulnerablePower",2},{"Damage",20},{"Cards",1}}, new Dictionary<string,int>{{"Damage",7}}),
        new("r_eeih.v1","鉄風毒の澄息",[Material.Ether,Material.Ether,Material.Iron,Material.Herb],"守りと循環","守りと敏捷を整え、深く息を継ぐ。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。カードを{Cards:diff()}枚引く。敏捷{DexterityPower:diff()}を得る。",
            new Dictionary<string,int>{{"Block",11},{"Cards",2},{"DexterityPower",2}}, new Dictionary<string,int>{{"Block",4}}),
        new("r_eeip.v1","鉄火風の静座",[Material.Ether,Material.Ether,Material.Iron,Material.Powder],"守りと循環","重みと熱を纏いながら、静かに整える。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。カードを{Cards:diff()}枚引く。筋力{StrengthPower:diff()}を得る。",
            new Dictionary<string,int>{{"Block",11},{"Cards",2},{"StrengthPower",1}}, new Dictionary<string,int>{{"Block",4}}),
        new("r_eehp.v1","毒火風の残息",[Material.Ether,Material.Ether,Material.Herb,Material.Powder],"守りと循環","三種の気配を纏った、万能の一息。",2,ForgeKind.Skill,ForgeTarget.Self,
            "{Block:diff()}ブロックを得る。カードを{Cards:diff()}枚引く。敏捷{DexterityPower:diff()}を得る。筋力{StrengthPower:diff()}を得る。",
            new Dictionary<string,int>{{"Block",7},{"Cards",2},{"DexterityPower",2},{"StrengthPower",1}}, new Dictionary<string,int>{{"Block",3}}),
        new("r_ihpe.v1","四相統合・賢者の一撃",[Material.Iron,Material.Herb,Material.Powder,Material.Ether],"切り札","四つの素材全てを注ぎ込む、錬金術師の集大成。",3,ForgeKind.Attack,ForgeTarget.Enemy,
            "{Damage:diff()}ダメージ。{Block:diff()}ブロックを得る。毒{PoisonPower:diff()}を与える。カードを{Cards:diff()}枚引く。相を{AdvancePhase:diff()}つ進める（地→水→火→風）。",
            new Dictionary<string,int>{{"Damage",16},{"Block",8},{"PoisonPower",6},{"Cards",1},{"AdvancePhase",1}}, new Dictionary<string,int>{{"Damage",6}},Exhaust:true)
    }.Select(Balance).ToArray());

    private static readonly HashSet<string> CommonCraftableIds = [
        "siege_shell.v1", "recycling_reactor.v1", "toxic_blast.v1", "distilled_venom.v1", "aether_nova.v1"
    ];
    public static IReadOnlyList<ForgeFormula> Craftable { get; } = All
        .Where(f => f.Materials.Count >= 3 || CommonCraftableIds.Contains(f.Id)).ToArray();

    // Higher tiers previously multiplied the cheap tier's permanent stats. Keep those cards loadable,
    // but cap raw scaling so rarity buys a new combination or timing tool rather than an early win condition.
    private static ForgeFormula Balance(ForgeFormula formula)
    {
        if (formula.Materials.Count < 3) return formula;
        var values = new Dictionary<string,int>(formula.Values);
        int cap = formula.Materials.Count == 3 ? 1 : 2;
        if (values.ContainsKey("StrengthPower")) values["StrengthPower"] = Math.Min(values["StrengthPower"], cap);
        if (values.ContainsKey("DexterityPower")) values["DexterityPower"] = Math.Min(values["DexterityPower"], cap);
        var upgrade = new Dictionary<string,int>(formula.Upgrade);
        if (upgrade.ContainsKey("StrengthPower")) upgrade["StrengthPower"] = Math.Min(upgrade["StrengthPower"], 1);
        if (upgrade.ContainsKey("DexterityPower")) upgrade["DexterityPower"] = Math.Min(upgrade["DexterityPower"], 1);
        return formula with { Values = values, Upgrade = upgrade };
    }
    public static ForgeFormula Get(string id) => All.SingleOrDefault(f=>f.Id==id)
        ?? throw new InvalidDataException($"未対応の錬成定義です：{id}。カードを初期化しません。");
}
